Prefs[TASK[28635] Create UI (Check In Screen)
awesome-academy/Travel-App pull request #25
Opened 2020-09-18 09:06 UTC by hieuna20168192

## Related Tickets
- [#Task 28635: Create UI (Check In Screen)](https://edu-redmine.sun-asterisk.vn/issues/28635)

## WHAT
- Create UI (Check In Screen)
## HOW
- Create UI (Check In Screen)
## WHY

## Evidence (Screenshot or Video)

<img src = "https://user-images.githubusercontent.com/45426479/93579466-b396c780-f9c8-11ea-8c31-2adcdc49996b.png" width = "270" height = "480"> 
<img src = "https://user-images.githubusercontent.com/45426479/93579521-c3161080-f9c8-11ea-8143-5bdfe592cfaf.png" width = "270" height = "480"> 
## Performance (Optional)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (HuyTQ)
--- | --- | --- | --- | --- | ---
General |Code should be self-explanatory. | Get a feel of story reading, while going through the code. Use appropriate name for variables, functions and classes. If you are taking more time to understand the code, then either code needs refactoring or at least comments have to be written to make it clear. | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
General |Is this function or class too big? If yes, is the function or class having too many responsibilities? | | NO |<li>- [x] no</li>|<li>- [x] no</li>  
General | Does the code follow DRY?: Do not Repeat Yourself | Is there any redundant or duplicate code? DRY (Do not Repeat Yourself) principle: The same code should not be repeated more than twice. Consider reusable services, functions and components. Consider generic functions and classes. | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
General |Exception handling and cleanup (dispose) resources | | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
General | Does the code build and execute correctly? | | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
Conventions | Does the source code have end-line errors? | | NO |<li>- [x] no</li>|<li>- [x] no</li>  
Conventions | No hard coding, use constants/configuration values | | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/tree/master/eng/android | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [x] yes</li>|<li>- [x] yes</li>  
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(List gem, library third party add new)*

*(Other notes)*

2020-09-18 09:11 UTC, quockhanhng commented on app/src/main/java/com/sunasterisk/travelapp/ui/adapter/CheckInViewPagerAdapter.kt
> +        this.fragments = fragments
```suggestion
        this.fragments.clear()
        this.fragments.addAll(fragments)
```

2020-09-18 09:14 UTC, quockhanhng commented on app/src/main/java/com/sunasterisk/travelapp/ui/checkin/BookRoomFragment.kt
> +        fun newInstance() = BookRoomFragment()
sao không gọi thẳng từ main constructor anh

2020-09-18 09:31 UTC, nogogold1998 requested changes

2020-09-18 09:31 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/custom/BackdropViewPager.kt
> +        }
```suggestion
        when (view.id) {
            R.id.imageViewStep -> slideFrontLayout()
            R.id.materialButtonContinue -> onNextPage()
            toolbarNavigation?.id -> handBackPress()
        }
```

2020-09-18 09:31 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/custom/BackdropViewPager.kt
> +        if ((currentPos < checkInViewPagerAdapter.count - 1)) {
```suggestion
        if (currentPos >= checkInViewPagerAdapter.count - 1) return
```

2020-09-18 11:32 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/ui/checkin/BookRoomFragment.kt
> +        fun newInstance() = BookRoomFragment()
ok em, chỗ này bị thừa

2020-09-18 16:34 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/adapter/CheckInViewPagerAdapter.kt
> +    private val fragments = mutableListOf<Fragment>()
T không chắc là có đc giữ `Fragment` không? Có thể bị `memory-leak`. Cái này hỏi Huy nhé, t cũng muốn biết

2020-09-18 16:34 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/checkin/CheckInActivity.kt
> +        val listFragments = mutableListOf<Fragment>(
```suggestion
        val listFragments = listOf(
```

2020-09-18 16:34 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/checkin/CheckInActivity.kt
> +        val listFragmentTitle = mutableListOf(
```suggestion
        val listFragmentTitle = listOf(
```

2020-09-18 16:34 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/custom/SwipeControllableViewPager.kt
> +        scroller.set(this, FastOutSlowInScroller(context, FastOutSlowInInterpolator()))
```suggestion
        val scroller = ViewPager::class.java.getDeclaredField("mScroller")
        try {
            scroller.isAccessible = true
            scroller.set(this, FastOutSlowInScroller(context, FastOutSlowInInterpolator()))
        } finally {
            scroller.isAccessible = false
        }
```

2020-09-18 16:34 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/custom/SwipeControllableViewPager.kt
> +        scroller.set(this, FastOutSlowInScroller(context, FastOutSlowInInterpolator()))
Thêm nữa là cái `mScroller` là hard code nhé

2020-09-18 16:34 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/utils/ViewExt.kt
> +}
```suggestion
fun Toolbar.getToolbarNavigationButton() =
    (0 until this.childCount).asSequence()
         .map(this::getchildAt)
         .firstOrNull { it is ImageButton }
```
Thử thế này xem

2020-09-19 07:38 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/ui/adapter/CheckInViewPagerAdapter.kt
> +    private val fragments = mutableListOf<Fragment>()
ok ông, t truyền vào supportFragmentManager, check thì thấy configuration change, onDetach của bọn child fragments ko chạy, trong phạm vi bọn t set màn hình hướng dọc thôi

2020-09-19 07:48 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/utils/ViewExt.kt
> +}
ok ông, gọn hơn rất nhiều

2020-09-19 11:04 UTC, merged