Prefs [TASK][28546]: Apply MVP Structure Template
awesome-academy/Travel-App pull request #3
Opened 2020-09-03 09:56 UTC by hieuna20168192

## Related Tickets
- [#{28546}: {}]({})

## WHAT
- Apply MVP Structure Template
## HOW
- Apply MVP Structure Template
## WHY

## Evidence (Screenshot or Video)

## Performance (Optional)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
General |Code should be self-explanatory. | Get a feel of story reading, while going through the code. Use appropriate name for variables, functions and classes. If you are taking more time to understand the code, then either code needs refactoring or at least comments have to be written to make it clear. | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
General |Is this function or class too big? If yes, is the function or class having too many responsibilities? | | NO |<li>- [ ] no</li>|<li>- [ ] no</li>  
General | Does the code follow DRY?: Do not Repeat Yourself | Is there any redundant or duplicate code? DRY (Do not Repeat Yourself) principle: The same code should not be repeated more than twice. Consider reusable services, functions and components. Consider generic functions and classes. | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
General |Exception handling and cleanup (dispose) resources | | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
General | Does the code build and execute correctly? | | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Conventions | Does the source code have end-line errors? | | NO |<li>- [ ] no</li>|<li>- [ ] no</li>  
Conventions | No hard coding, use constants/configuration values | | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/tree/master/eng/android | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(List gem, library third party add new)*

*(Other notes)*

2020-09-04 01:34 UTC, huytq-0932 commented on app/build.gradle
>  }
![image](https://user-images.githubusercontent.com/53286739/92189645-64f61300-ee89-11ea-9159-57b85f7df2be.png)

2020-09-04 01:40 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/data/model/Hotel.kt
> +}
Thêm 1 dòng trống vào cuối mỗi file tránh lỗi như này nhé

2020-09-04 02:57 UTC, nogogold1998 requested changes

2020-09-04 02:57 UTC, nogogold1998 commented on app/build.gradle
> +
blank line

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/model/Restaurant.kt
> +}
```suggestion
class Restaurant

```

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/HotelDataSource.kt
> +}
Thêm dòng trống

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/HotelRepository.kt
> +    }
```suggestion
    override fun getHotels(callback: HotelDataSource.LoadHotelsCallback) = Unit
```

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/HotelRepository.kt
> +}
Thêm dòng trống

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/remote/HotelsRemoteDataSource.kt
> +}
```suggestion
class HotelsRemoteDataSource

```
thêm dòng trống

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/local/HotelsLocalDataSource.kt
> +}
```suggestion
class HotelsLocalDataSource

```
thêm dòng trống

2020-09-04 02:57 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseActivity.kt
> +        initComponent()
```suggestion
        initComponents()
```

2020-09-04 07:01 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseActivity.kt
> +    protected abstract val layoutResource: Int
```suggestion
    @get:LayoutRes
    protected abstract val layoutResource: Int
```

2020-09-04 07:01 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseRecyclerAdapter.kt
> +        diffResult.dispatchUpdatesTo(this)
Đoạn này để làm gì thế ?

2020-09-04 09:07 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseRecyclerAdapter.kt
> +        diffResult.dispatchUpdatesTo(this)
Đoạn này update lại adapter với items list mới

2020-09-04 09:40 UTC, thonc-2135 commented on app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0'
hình như dùng material là n có luôn recycler view r nhỉ

2020-09-04 09:40 UTC, thonc-2135 commented on app/build.gradle
> +    implementation 'de.hdodenhof:circleimageview:2.2.0'
Suggest: có thể dùng glide để tạo circle image , k nhất thiết phải thêm thư viện này

2020-09-04 09:40 UTC, thonc-2135 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BasePresenter.kt
> +    fun start() {
đặt tên cụ thể hơn chút được không, start cái gì nhỉ

2020-09-04 09:40 UTC, thonc-2135 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/DiffUtilCallback.kt
> +    override fun getOldListSize(): Int = oldItems.size
```suggestion
    override fun getOldListSize() = oldItems.size
```

2020-09-04 09:40 UTC, thonc-2135 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/DiffUtilCallback.kt
> +    override fun areItemsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean =
```suggestion
    override fun areItemsTheSame(oldItemPosition: Int, newItemPosition: Int) =
```

2020-09-04 12:11 UTC, huytq-0932 commented on app/build.gradle
> +    implementation 'de.hdodenhof:circleimageview:2.2.0'
không được dùng thư viện ngoài Glide

2020-09-05 12:20 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseRecyclerAdapter.kt
> +        if (position in 0 until itemCount) items[position] else null
```suggestion
    protected fun getItem(position: Int) = items.getOrNull(position)
```

2020-09-05 12:20 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseRecyclerAdapter.kt
> +    override fun getItemCount(): Int = items.size
```suggestion
    override fun getItemCount() = items.size
```

2020-09-05 12:20 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/DiffUtilCallback.kt
> +    override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int): Boolean =
```suggestion
    override fun areContentsTheSame(oldItemPosition: Int, newItemPosition: Int) =
```

2020-09-07 02:57 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +    }
viết constructor kiểu kotlin 
```suggestion
class NetworkError(e: Throwable) : Throwable(e) {
```

2020-09-07 02:58 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +}
Lớp này dùng để làm gì nhỉ, dùng khi nào thế?

2020-09-07 02:59 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +                DEFAULT_ERROR_MESSAGE) as String
Dùng when {} Kotlin đoạn này nhé

2020-09-07 02:59 UTC, hieuna20168192 commented on app/build.gradle
> +    implementation 'androidx.recyclerview:recyclerview:1.1.0'
vâng, androidX có luôn ạ

2020-09-07 02:59 UTC, hieuna20168192 commented on app/build.gradle
> +    implementation 'de.hdodenhof:circleimageview:2.2.0'
Ok

2020-09-07 03:01 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPActivity.kt
> +        }
```suggestion
        val msg = message ?: getString(R.string.default_error_message)
       
```

2020-09-07 03:13 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +}
Lớp này dùng trong trường hợp khi requestAPI trong remote data source throw exception, nếu dùng HttpsUrlConnection thì nó ném ra exception luôn thay vì throwable

2020-09-07 03:24 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +}
Ném ra Exception thì sao nhir?

2020-09-07 03:27 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BasePresenter.kt
> +        val errorMsg = networkError.appErrorMessage!!
không được bỏ qua check null

2020-09-07 03:27 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BasePresenter.kt
> +    }
https://developer.android.com/kotlin/style-guide#expressions

2020-09-07 03:28 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPFragment.kt
> +            showSnackBarMessage(message)
```suggestion
        if (!message.isNullOrEmpty())  showSnackBarMessage(message)
```

2020-09-07 03:28 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPFragment.kt
> +            Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
https://developer.android.com/kotlin/style-guide#braces

2020-09-07 03:29 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPFragment.kt
> +        progressDialog = (context as Activity).createProgressDialog()
```suggestion
        progressDialog = activity?.createProgressDialog()
```

2020-09-07 03:29 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/utils/AppCompatActivityExt.kt
> +}
Dùng scope function

2020-09-07 03:30 UTC, huytq-0932 commented on app/src/main/res/layout/progress_dialog.xml
> +</RelativeLayout>
Tại sao ở đây lại dùng RelativeLayout mà không dùng các loại Layout khác thế

2020-09-07 03:30 UTC, huytq-0932 commented on app/src/main/res/values/colors.xml
> +    <color name="white">#ffffff</color>
màu này chưa dùng đến

2020-09-07 03:31 UTC, huytq-0932 commented on app/src/main/res/values/colors.xml
> +    <color name="divider">#E5E5E5</color>
Đặt theo tên màu 
http://chir.ag/projects/name-that-color/#E5E5E5

2020-09-07 03:31 UTC, huytq-0932 commented on app/src/main/res/values/colors.xml
> +    <color name="black_effective">#2a2a2a</color>
```suggestion
    <color name="color_black_effective">#2a2a2a</color>
```

2020-09-07 03:32 UTC, huytq-0932 commented on app/src/main/res/values/strings.xml
> +    <string name="label_refresh">Refresh</string>
Conventions 3.2.2 
https://github.com/framgia/coding-standards/blob/master/eng/android/codingstyleguide.md

2020-09-07 03:33 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPFragment.kt
> +        }
Dùng elvis operator

2020-09-07 03:38 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +}
Vì Exception extends Throwable, khi ném ra exception thì presenter dùng lớp này để lấy appErrorMessage -> update view (thông báo lỗi)

2020-09-07 03:57 UTC, hieuna20168192 commented on app/src/main/res/layout/progress_dialog.xml
> +</RelativeLayout>
Thường thì dùng RelativeLayout để tránh layout lồng nhau (vd: LinearLayout). Ở đây chỉ có mỗi 1 child view là ProgressBar và để cho tiện set nó ở chính giữa nên t dùng vậy

2020-09-07 03:57 UTC, hieuna20168192 commented on app/src/main/res/values/colors.xml
> +    <color name="white">#ffffff</color>
Ok, đã xóa theo Lint

2020-09-07 04:56 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +        }
T không hiểu lắm ô giải thích

2020-09-07 05:04 UTC, aug16vcc commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +        }
T không hiểu. Ô giải thích đc k

2020-09-07 05:04 UTC, aug16vcc commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPActivity.kt
> +            showSnackBarMessage(message)
```suggestion
        if (!message.isNullOrEmpty()) showSnackBarMessage(message)
```

2020-09-07 05:04 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPActivity.kt
> +        getString(R.string.error_default_message)
```suggestion
        val msg = message ?: getString(R.string.error_default_message)
```

2020-09-07 05:04 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPFragment.kt
> +        }
```suggestion
        if (!message.isNullOrEmpty()) showSnackBarMessage(message)
```
Có thể sửa nhé

2020-09-07 05:04 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/utils/AppCompatActivityExt.kt
> +}
```suggestion
fun Activity.createProgressDialog() = Dialog(this).apply {
    show()
    setContentView(R.layout.progress_dialog)
    setCancelable(false)
    setCanceledOnTouchOutside(false)
}
```

2020-09-07 05:32 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +        }
Ok, đoạn này thiếu case **e is IOException**, hàm này trả về 1 message thông báo lỗi cho user dựa theo exception có thể ném ra khi request remote API

2020-09-07 05:53 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +}
Thế sao không dùng luôn Exception mà HttpUrlConnection ném ra mà phải tạo thêm lớp này để làm gì nhỉ?

2020-09-07 05:54 UTC, huytq-0932 commented on app/src/main/res/layout/progress_dialog.xml
> +</RelativeLayout>
Dùng FrameLayout nhé 
RelativeLayout vẽ rất cồng kềnh

2020-09-07 05:54 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +            }
1. `Unreachable code at line 12` vì `IOException` là con của `Exception`
2. `when` trả về kiểu `String` xong dùng ở đâu?

2020-09-07 05:54 UTC, nogogold1998 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPActivity.kt
> +            Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
Nên `Context extension`

2020-09-07 05:56 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseMVPActivity.kt
> +            Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
Chú ý conventions 
https://developer.android.com/kotlin/style-guide#braces

2020-09-07 05:57 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BasePresenter.kt
> +        val errorMsg = if (networkError.appErrorMessage != null) networkError.appErrorMessage else ""
Dùng elvis operator nhé

2020-09-07 06:01 UTC, thonc-2135 commented on app/src/main/res/layout/progress_dialog.xml
> +        android:id="@+id/progress_loading"
sai cách đặt tên nhé

2020-09-07 06:01 UTC, thonc-2135 commented on app/src/main/res/layout/progress_dialog.xml
> +<RelativeLayout
vẫn k nên dùng ralative nhé

2020-09-07 06:01 UTC, thonc-2135 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BaseContract.kt
> +
remove blank

2020-09-07 06:01 UTC, thonc-2135 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +    }
thấy ở string.xml có r mà sao còn cần khai báo thêm lm gì thế

2020-09-07 06:01 UTC, huytq-0932 commented on app/src/main/java/com/sunasterisk/travelapp/ui/base/BasePresenter.kt
> +        val errorMsg = if (networkError.appErrorMessage != null) networkError.appErrorMessage else ""
```suggestion
        val errorMsg = networkError.appErrorMessage ?: ""
```

2020-09-07 06:02 UTC, huytq-0932 commented on app/src/main/res/values/colors.xml
>      <color name="colorAccent">#03DAC5</color>
cả những màu trên nữa 
```suggestion
    <color name="colorPrimary">#6200EE</color>
    <color name="colorPrimaryDark">#3700B3</color>
    <color name="color_accent">#03DAC5</color>
```

2020-09-07 06:14 UTC, hieuna20168192 commented on app/src/main/java/com/sunasterisk/travelapp/data/source/network/NetworkError.kt
> +}
Vì exception khó hiểu tới người dùng, hàm này trả về 1 số thông báo lỗi dễ hiểu hơn

2020-09-07 07:25 UTC, nogogold1998 approved these changes

2020-09-07 07:39 UTC, merged